#ifndef SCANNER_H
#define SCANNER_H

typedef enum ScannerToken {
	TOK_EOF = 0,
	TOK_ERROR = 256,
	TOK_ERROR_UNCLOSED_COMMENT,

	TOK_KW_INT,
	TOK_KW_FLOAT,
	TOK_KW_DOUBLE,
	TOK_KW_CHAR,
	TOK_KW_VOID,
	TOK_KW_IF,
	TOK_KW_ELSE,
	TOK_KW_WHILE,
	TOK_KW_FOR,
	TOK_KW_FOREACH,
	TOK_KW_RETURN,
	TOK_KW_BREAK,
	TOK_KW_CONTINUE,
	TOK_KW_FUN,
	TOK_KW_IN,
	TOK_KW_OUT,
	TOK_KW_CONST,
	TOK_KW_MATCH,
	TOK_KW_DO,
	TOK_KW_TRUE,
	TOK_KW_FALSE,
	TOK_KW_STR,
	TOK_KW_PRINT,
	TOK_KW_READ,
	TOK_KW_EXIT,
	TOK_KW_SYSTEM,

	TOK_IDENTIFIER,
	TOK_INT_LITERAL,
	TOK_FLOAT_LITERAL,
	TOK_STRING_LITERAL,
	TOK_CHAR_LITERAL,

	TOK_LEFT_SHIFT,
	TOK_RIGHT_SHIFT,
	TOK_INC,
	TOK_DEC,
	TOK_PLUS_ASSIGN,
	TOK_MINUS_ASSIGN,
	TOK_MUL_ASSIGN,
	TOK_DIV_ASSIGN,
	TOK_MOD_ASSIGN,
	TOK_LEFT_ASSIGN,
	TOK_RIGHT_ASSIGN,

	TOK_EQ,
	TOK_NEQ,
	TOK_LT,
	TOK_LE,
	TOK_GT,
	TOK_GE,

	TOK_AND,
	TOK_OR,
	TOK_NOT,

	TOK_PLUS,
	TOK_MINUS,
	TOK_MUL,
	TOK_DIV,
	TOK_MOD,

	TOK_LPAREN,
	TOK_RPAREN,
	TOK_LBRACE,
	TOK_RBRACE,
	TOK_LBRACKET,
	TOK_RBRACKET,
	TOK_COMMA,
	TOK_SEMICOLON,
	TOK_COLON
} ScannerToken;

const char *scanner_token_name(int token);

#endif // SCANNER_H